services:
  - type: web
    name: whatsapp-chatbot-jarurat
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
